### ISSUE TITLE
External Ressources Tags instead of fixed categories

### ISSUE THREAD

**Issue by alexanderniebuhr** [astrolicious/astro-tips.dev#146]
Instead of the fixed categories e.g. https://astro-tips.dev/resources/educational/
We would like to have tags, which can be added to all of our content. E.g. I want to add css & animations to one link, etc.

**Comment by hkbertoson** [comment]
Okay. So i understand what you are wanting. But im struggling to figure out exactly what it needs to look like? If that makes sense...

**Comment by wassfila** [comment]
if I may link my website, it' built with Astro lol and even if the blog entries in this context might not be built with the same component, I wanted to share the tags concept <https://www.homesmartmesh.com/>
Tags are freely assigned in frontmatter, then rendered in the blogs and blogs cards. As todo and I highly recommend is a filter, also if possible to make it small and visible in a fixed menu area.
This astro themes is another example for using tags but I find it a bit too hidden and many steps required to filter maybe because not only they have tags but also tags categories :) https://astro.build/themes/
